name: Generate daily snippets

permissions:
  contents: write

on:
  schedule:
    - cron: '0 9 * * *' # run daily at 09:00 UTC (adjust as needed)
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # allow pushing back using the token provided to the runner
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create daily snippet
        run: |
          python generate_daily.py --commit --message "chore: add daily snippet from action"

      - name: Push changes (using GITHUB_TOKEN)
        run: |
          set -e
          echo "Pushing changes using GITHUB_TOKEN (actions/checkout persisted credentials)"
          git push origin HEAD:${{ github.ref_name }}
